### ISSUE TITLE
Is this the repository to submit a compute-intensive bench that could benefit from multicore OCaml?

### ISSUE THREAD

**Issue by UnixJunkie** [OCamlPro/ocamlbench-repo#5]
I have an idea: in machine learning, computing the Gram matrix of a dataset
is something very useful and easy to parallelize.

I can submit the sequential code, the parmap version, the parany version,
an example dataset, and hope that some good will will provide the multicore OCaml version.

**Comment by lthls** [comment]
Thanks for your interest ! This repo was created for the purpose of benchmarking flambda.
For benchmarking multicore, they have set up [sandmark](https://github.com/ocaml-bench/sandmark), which I assume would gladly accept your proposition.
I you want to take the time to submit a PR to our repo, we would of course review it, but since you specifically mention multicore it would be faster to go directly to sandmark.

**Comment by UnixJunkie** [comment]
ok, thanks a lot for the info.

**Comment by UnixJunkie** [comment]
I just sent them a link to this:
https://github.com/UnixJunkie/gram-matrix-bench
The code is still fresh. :)
